name: "Build"
on:
  pull_request:
  push:
jobs:
  # uses nix
  nix_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: cachix/install-nix-action@v31
      - run: nix flake check -L
      - run: nix flake show -L
      - run: nix build -L .#combined
      - name: Create ZIP
        run: |
          export ZIP="$PWD/slidev-slides.zip"
          cd result
          zip -r "${ZIP}" .
          cd -
      - name: Upload ZIP with Slides
        uses: actions/upload-artifact@v4
        with:
          name: Slidev Slides (ZIP)
          path: |
            slidev-slides.zip
